### ISSUE TITLE
Checking dependencies when modules are required

### ISSUE THREAD

**Issue by dlebauer** [PecanProject/pecan#109]
build.sh will not run without the following on HPC systems:

```
module load netcdf nco R jags gdal
```

Some options:
1. place a message in "check dependences"? (e.g. instructing user to `echo "module load netcdf nco R jags gdal" > ~/.bashrc`) 
2. add a line to scripts/build.sh to load modules if module system is being used

```
if type module > /dev/null; then 
  module load netcdf/4.3.1.1 nco R/3.0.2 JAGS  gdal/1.10.1
fi
```

Suggestions?

**Comment by dlebauer** [comment]
Would it work to add `source ~/.bashrc` to the header of the `job.sh` (assuming that the modules are loaded in .bashrc)?

The module software does read `.modulerc` file - though documentation and google results for its use are sparse

**Comment by robkooper** [comment]
Biggest problem with that is you have to make sure people write their .bashrc correct. Can you check to see what happens if you use  your .bash_profile for loading the modules. That should be loaded when the job is started. This also depends on what shell you use, but the qsub command in pecan forces it to be bash.

**Comment by robkooper** [comment]
For an example of the .modulerc file see https://github.com/AntoineD/dotfiles/blob/master/.modulerc

**Comment by dlebauer** [comment]
@robkooper If my `.bash_profile` includes the lines:

```
# Get the aliases and functions                                                
if [ -f ~/.bashrc ]; then
        . ~/.bashrc
fi
```

Wouldn't this be the same as adding the module_load commands there?

If I use `.profile` or `.modulerc` would I also need to load it in `.bash_profile`?

**Comment by robkooper** [comment]
.profile and .bash_profile are loaded for a login script. I think the .profile is the same as .bash_profile, except it is also loaded by sh which is not always the same as bash. The file .bash_profile is only read by bash.

Unlike .profile/.bash_profile, .bashrc is loaded for an interactive session. So in theory you should only load your .bashrc if you know for sure you are on an interactive shell, meaning one that has a command prompt.

That is the theory, but I always have a hard time with it and do the same as you. Just be aware that changing the prompt by lead to errors.

**Comment by dlebauer** [comment]
I think `.profile` is not read if `.bash_profile` is present.

So I put the module loading and seting of `R_LIBS_USER` in `.bash_profile`. Here is my setup for multiple servers: https://github.com/dlebauer/dotfiles/blob/master/bash_profile

for specifying which modules are loaded conditional on the server, but independent of which node is being used (since `$HOSTNAME` changes on slave nodes I replace with `$PBS_O_HOST`), I use this:

```sh
for myhostname in "biocluster.igb.illinois.edu" "ebi-cluster.igb.illinois.edu"; do
    if [[ "$HOSTNAME" == $myhostname || "$PBS_O_HOST" == $myhostname ]] ; then
      module load nco/4.4.8 netcdf/4.3.3.1 gdal/1.11.2 udunits/2.1.24 R/3.1.1 JAGS gsl emacs
    fi
done
```

**Comment by tonygardella** [comment]
@ashiklom Do we/Should we have warnings or messages in the Makefile to help people edit their .bashrc or .profile to load certain modules or download modules they don't have?

**Comment by ashiklom** [comment]
We could certainly try, but it's a bit nontrivial, since we'd have to weave through a bunch of nested R package dependencies to see if things have system dependencies. Probably a good place to start would be to have an evolving bash script called by `make` that checks for the presence of system dependencies.

In theory, this is the sort of thing that the [GNU build system](http://www.gnu.org/software/automake/manual/html_node/Autotools-Introduction.html#Autotools-Introduction) exists to handle. Learning how to use it has been on my to-do list forever, but I've never really found the time.

**Comment by tonygardella** [comment]
@ashiklom Ok sounds good. I'll keep this issue around in case the topic of dependencies comes up because it seems to come up a lot.

**Comment by infotroph** [comment]
I'm going to close this long-inactive issue. The needed configuration is always going to be user-specific, and the PEcAn architecture has changed enough in the meantime that it's not clear whether any of the approaches proposed here would still work. If more action is needed, please open a new issue.
