### ISSUE TITLE
conversion of CO2 values in older met files

### ISSUE THREAD

**Issue by istfer** [PecanProject/pecan#1206]
With [this commit](https://github.com/PecanProject/pecan/pull/646/commits/8c55736a816f450b1de0e975cda94faa6df83a5a) a CO2  conversion issue was fixed in the past. But there are files in our systems that were processed before this commit. So now the CO2 values in those files are multiplied by `1e6` twice in met2model conversions. Not sure how we want to handle this.

**Comment by mdietze** [comment]
Can you identify all the relevant files (e.g. a search by date relative to when the bug was fixed?)  Is this a modest number of files that we can fix by hand (rerun met.process with overwrite=TRUE) or something we'll need to script

**Comment by istfer** [comment]
I'll take a look at this after AGU

**Comment by bcow** [comment]
I can help with that also after AGU because it seems like it would coincide with some database/met cleanup that I should do. I had proposed removing everything that was made before a stable version of met.process was released. Can't think of the date off the top of my head but I have it in my notes.

**Comment by istfer** [comment]
cool, I can join the cleanup for my orphan posteriors and likelihoods from all my PDA tests
