### ISSUE TITLE
Meta-analysis AUTO broken ... again

### ISSUE THREAD

**Issue by mdietze** [PecanProject/pecan#1217]
Meta-analysis seems to be running for every run again. Need to add debugging this so it only runs when needed back on the list. I'm seriously tempted to just remove the MA block from the default run specification so that users have to turn it on during advanced edit.

**Comment by tonygardella** [comment]
Taking out the  meta-anlysis tags in the pecan.xml skipped that step but made write.configs fail:

```
2017-07-10 10:46:38 INFO   [get.parameter.samples] : 
   Selected PFT(s): populus 
Warning in rm(prior.distns, post.distns, trait.mcmc) :
  object 'prior.distns' not found
Warning in rm(prior.distns, post.distns, trait.mcmc) :
  object 'post.distns' not found
Warning in rm(prior.distns, post.distns, trait.mcmc) :
  object 'trait.mcmc' not found
Warning in readChar(con, 5L, useBytes = TRUE) :
  cannot open compressed file '/home/carya/output//PEcAn_99000000001/pft/populus/prior.distns.Rdata', probable reason 'No such file or directory'
Error in readChar(con, 5L, useBytes = TRUE) : cannot open the connection
```
Looks like none of the prior data or parameter info was saved to the pft directory. Next step is to look into why none of the trait data was generated without the meta analysis.

**Comment by mdietze** [comment]
Well, if we don't run the MA we don't need to run the trait query either, but we do need to query to get the latest posteriors. They would no longer be in the PFT directory of that run, but in the directory of the run when the MA was updated.

**Comment by ashiklom** [comment]
Bump!

So I think I may have made some progress on this: `get.trait.data`, which I think is responsible for figuring out whether or not to run the meta analysis, looks for the `trait.data.Rdata`, `prior.distns.Rdata`, and either `species.csv` or `cultivar.csv`. However, these files don't come up in the `dbfile.check` (nor, for that matter, does `post.distns.Rdata` because it's a symlink, but the file it points to -- `post.distns.MA.Rdata` -- does come up), so I think there is a problem with how they are registered somewhere. I'll keep digging...

https://github.com/PecanProject/pecan/blob/1676d5cec6593dea0bdb98c8ba22eadf1e0ceccb/base/db/R/get.trait.data.R#L128-L129
