### ISSUE TITLE
Cannot download Ameriflux data for existing years

### ISSUE THREAD

**Issue by mccabete** [PecanProject/pecan#1260]
## Description
When I tried to use Ameriflux as a met driver for years I know exist, I get an error:
" Error in logger.severe("Could not download data for", site, "for the year",  : Could not download data for US-KS1 for the year 2005 "
Example runs include: [1000003253](http://128.197.168.115/pecan_tmccabe/08-finished.php?workflowid=1000003253), [1000003254](http://128.197.168.115/pecan_tmccabe/08-finished.php?workflowid=1000003254) & [1000003295](http://128.197.168.115/pecan_tmccabe/08-finished.php?workflowid=1000003295) 

## Context
@ankurdesai @jsimkins2 
I only get this error running it at Kennedy Space Center, so this is likely site-spesific.  However, using Ameriflux as a met source only worked successfully Austin Cary. I experienced several errors using different met. To recreate the runs or see a summary of the error they're listed [here](https://docs.google.com/spreadsheets/d/1zGwLAkCBOABzjJZhEjZsfCVrr9zpJBTasZwyuOc69xI/edit?usp=sharing).

**Comment by ankurdesai** [comment]
Hi, US-KS1 for 2005 is not on the Ameriflux FTP site:
  http://cdiac.ornl.gov/ftp/ameriflux/data/Level2/Sites_ByID/US-KS1/with_gaps/ <http://cdiac.ornl.gov/ftp/ameriflux/data/Level2/Sites_ByID/US-KS1/with_gaps/>

Also similar on Ameriflux LBL server, but in general try both download.Ameriflux and download.AmerifluxLBL, as the former is being deprecated for the latter in Ameriflux.

**Comment by mdietze** [comment]
A tad off topic, but ran into Deb Agarwal last week at the NEON workshop and it sounds like there's going to be a big update to Ameriflux in the not-to-distant future. To date the LBNL server hasn't been kept up to date beyond what was on the ORNL server, but that should change soon, at which point we'll really want to shift to AmerifluxLBL as our default for download

In the mean time, I think this issue can be closed since there's not a bug in PEcAn itself.

**Comment by ankurdesai** [comment]
@mccabete Same issue with US-KS1 - there is no data past 2003. There is for US-KS2. The issue with US-Akn seems like an actual bug. I will submit a PR to fix it soon.
