### ISSUE TITLE
CRUNCEP ocean mask excludes coastal sites

### ISSUE THREAD

**Issue by mccabete** [PecanProject/pecan#1265]
The met driver CRUNCEP has a 0.5 * 0.5 resolution, so certain coastal sites (Like Kennedy Space Center, for example, but I'm sure there are others) are treated as ocean and fail to provide met data. 

## Description

The two suggestions brought up at todays meeting were to automatically shift to the nearest land grid cell instead of just returning an error. That, or interpolate from multiple surrounding land grid cells. 

## Context

This would be useful to prevent hacks like the one I'm currently using where you  just create a fake site that's in the next nearest grid cell.

This will likely be an issue for any course-resolution met product. I'm not sure if we already solved this problem elsewhere.

**Comment by ashiklom** [comment]
Bumping this because it _also_ shows up in coastal areas next to large lakes. Case in point -- I was trying to do runs at UMBS site, whose coordinates round into the adjacent lake.

For reference, [here](https://thredds.daac.ornl.gov/thredds/catalog/ornldaac/1220/catalog.html?dataset=1220/mstmip_driver_global_hd_landwatermask_v1.nc4) is the link to the CRUNCEP land-water mask that we should use in solving this problem.

**Comment by ashiklom** [comment]
Closing because this should have been resolved in #2155. I was able to use PEcAn to do runs at UMBS. @mccabete let me know if that code doesn't work for the Kennedy Space Center or other coastal sites.
