### ISSUE TITLE
Enable BioCro tests to run in the web interface

### ISSUE THREAD

**Issue by dlebauer** [PecanProject/pecan#1266]
## Description

I am assuming that

```sh
.../web/workflow.R --settings pecan64.biocro.xml
```

works on the Virtual Machine.

The next step is to enable BioCro to work in the web interface - 

I believe there are two steps to enabling this
1. get the location of the binary executable (`pointbiocro.Rscript`) from BETYdb given the model name in settings (probably already works)
2. hook into the met workflow.

I think 2 will be the bulk of the work

## Completion Criteria

* [x] confirm that pecan64.biocro.xml works on vanilla VM
* [ ] identify and debug errors that occur when trying to use PEcAn met workflow
   * [ ] BioCro works with NARR through web interface
   * [x] BioCro works with Ameriflux through web interface

**Comment by infotroph** [comment]
Working on this in https://github.com/infotroph/pecan/tree/ckb-biocro, but the branch is messy and probably needs to be split into a couple of separate PRs. I will update this comment once that's done.

Mostly working test instance  at [http://54.211.130.240](http://54.211.130.240) -- currently works with Bondville met and all PFTs I've tried, as long as you:

 1. specify an end date no later than 2004-12-30, or more precisely don't specify a 366-day year. Does BioCro handle leap days?
2. Choose "edit pecan.xml" and change the ensemble variable from NPP to one of the variables returned by model2netcdf.BIOCRO.R: TotLivBiom, RootBiom, StemBiom, Yield, Evap, TVeg, LAI.

**Comment by dlebauer** [comment]
> Does BioCro handle leap days?

I don't think BioCro cares about leap days ... it just runs along the met data. 

PR https://github.com/PecanProject/pecan/pull/1312 should add NPP to BioCro output, though I haven't tested it.

**Comment by infotroph** [comment]
* [Works](http://184.73.65.42/pecan/08-finished.php?workflowid=99000000143) with AmerifluxLBL
* [Works](http://184.73.65.42/pecan/08-finished.php?workflowid=99000000136) with FLUXNET2015
* [Fails](http://184.73.65.42/pecan/05-running.php?workflowid=99000000142) with NARR because browndog.met [only handles models explicitly listed in met.process.R](https://github.com/PecanProject/pecan/blob/master/modules/data.atmosphere/R/met.process.R#L295)
* [fails](http://184.73.65.42/pecan/05-running.php?workflowid=99000000144) with CRUNCEP because CF files are missing reference times (#1347)
* Other sources not yet tested

@dlebauer OK to close this?

**Comment by dlebauer** [comment]
@infotroph 
If it would take less than a few hours to work with NARR and CRUNCEP, could you please do that?

* NARR looks like it could be a quick fix (@robkooper is this accurate?
* For CRUNCEP, is it trivial to get the reference time from the file name so we don't have to wait for #1347?
