### ISSUE TITLE
How do we handle documenation for different PEcAn versions?

### ISSUE THREAD

**Issue by tonygardella** [PecanProject/pecan#1351]
Every time a new version of PEcAn comes out, documentation will be in sync with those changes. 

However, if someone has an older version or different version of PEcAn they will not have the correct documentation available to them

## Possible Implementation
Some possible solutions:

- Render all versions of documentation by having  deploy.sh point to tagged points in git history and give each version unique urls.

- Have the code available to render older versions of documentation if someone would like to.

Please discuss possible solutions .

**Comment by mdietze** [comment]
So my ideal solution would be the first option -- we have unique urls generated for master, devel, and any release-*.  Hopefully there's a regexp solution to the latter that won't require us to update deploy.sh every time we create a new release.

**Comment by robkooper** [comment]
We can use something like the following:
```
# find version if we are develop/latest/release and if should be pushed
BRANCH="$(git rev-parse --abbrev-ref HEAD)"
PUBLISH="NOPE"
if [ "$BRANCH" = "master" ]; then
  PUBLISH="yes"
  VERSION="latest"
elif [ "$BRANCH" = "develop" ]; then
  PUBLISH="yes"
  VERSION="develop"
elif [ "$( echo $BRANCH | sed -e 's#^release/.*$#release#')" = "release" ]; then
  PUBLISH="yes"
  VERSION="$( echo $BRANCH | sed -e 's#^release/\(.*\)$#\1#' )"
else
  PUBLISH="no"
  VERSION="local"
fi
```

Now we can use PUBLISH == "yes" to see if we need to publish and VERSION will contain where to publish it.

**Comment by mdietze** [comment]
Currently we don't seem to be generating release-specific documentation, just master and develop

http://pecanproject.github.io/documentation.html

which wasn't our plan and doesn't allow people to see the docs for old versions. Or, if we are generating release documentation, we don't seem to be putting it on the webpage.

Post-AGU this needs to be part of a general recommitment to updating the documentation.

**Comment by bpbond** [comment]
Might be useful to take a look at how a big project in our institute handles this.

https://github.com/JGCRI/gcam-doc
http://jgcri.github.io/gcam-doc/

Tagging my colleague @rplzzz to weigh in...

**Comment by rplzzz** [comment]
First, if you look in our [documentation repository](https://github.com/JGCRI/gcam-doc), you'll see two things.  First, all the markdown files that Jekyll converts into the html that is displayed online.  Second, there are are bunch of subdirectories named v4.2, v4.3, and so on.  Those are the archives of the old versions.  Any time we want to make a new release, we start by copying the current snapshot of the docs into a directory named for the version that we are archiving.  We only maintain documentation for major and minor releases; patch-level releases and unreleased branches don't get their documentation archived specially, though you could do so if you wanted to.

Next, if you look at one of the markdown [source files](https://raw.githubusercontent.com/JGCRI/gcam-doc/gh-pages/energy.md) you'll see some YAML at the top.  
```
---
layout: index
title: GCAM Energy System
prev: macro-econ.html
next: aglu.html
gcam-version: v4.4 
---
```
Jekyll uses this information when it generates the html page to display.  One of the things you can do is interpolate these variables into the output.  Here's an example from the template used to generate the doc pages:
https://github.com/JGCRI/gcam-doc/blob/gh-pages/_layouts/index.html#L22
```html
        <h1>GCAM {{page.gcam-version}} Documentation: {{page.title}}</h1>
```
The page variables get interpolated in at the braces, so for the page linked above this H1 tag would render as "GCAM v4.4 Documentation: GCAM Energy System".  Therefore, once you've archived the old documentation version, you just need to update the version variable in the pages at the top level of the docs.  This is easy enough to do with a perl one-liner something like `perl -pi -e 's/gcam-version: v4.4/gcam-version: v4.5/;' *.md`.

The last piece of the puzzle is to make the old versions available.  We include them as links at the bottom of our [table of contents](https://raw.githubusercontent.com/JGCRI/gcam-doc/gh-pages/toc.md)
```md
## Documentation for Older Versions of GCAM

* [GCAM-3](v3.2/toc.html)
* [GCAM-4.2](v4.2/toc.html)
* [GCAM-4.3](v4.3/toc.html)
```
By the way, you'll want to make sure you are using relative URLs for the internal links in your documentation, so that once you get down to, say, the v4.2 subdirectory, all links between pages stay in that subdir.

As for synchronizing releases between the docs and the code, what we do is to develop documentation for new features on branches named for those features.  Once we have a release candidate for the code, we create a new release branch on the documentation repository.  The first commit on that branch is the one that archives the old version and updates the version numbers in the current version.  Then you can merge the feature doc branches onto the release branch.  As long as documentation authors didn't monkey with the YAML block, they should merge cleanly, with the updated version number retained.  The only gotcha is that entirely new pages will go in as-is, so it's best to create new pages on feature branches with a bogus version number (e.g. "XYZ").  Then you can do a quick grep at the end of the process for any unset version numbers.  Finally, once the code release is ready, you can merge the release branch into Jekyll's main branch (probably either "master" or "gh-pages"), and the new docs will be live.

**Comment by robkooper** [comment]
Added as part of the season of docs project. This is a list of tasks for documentation that might be of interest.

**Comment by robkooper** [comment]
Closing this issue, we have older versions on the homepage, there was some discussion about this for the homepage redesign and we have docker specific containers for each version with the documentation.
