### ISSUE TITLE
Issue with error handling - if test dates are outside of model run dates

### ISSUE THREAD

**Issue by serbinsh** [PecanProject/pecan#1428]
A RTFM issue but if you, say, accidentally set the ensemble run outside of the model run dates then source workflow.R, it won't create the output dir and then we get this error:

```
2017-05-31 09:15:21 WARN   [check.database.settings] :
   Will not write runs/configurations to database.
2017-05-31 09:15:21 WARN   [check.bety.version] :
   Last migration 20170415183619 is more recent than expected
   20141009160121. This could result in PEcAn not working as expected.
2017-05-31 09:15:22 SEVERE [fn] :
   Start year of ensemble should come after the start.date of the run
Warning in file(file, ifelse(append, "a", "w")) :
  cannot open file '/data/Model_Output/fates_pecan_runs/new_test_2/STATUS': No such file or directory
Error in file(file, ifelse(append, "a", "w")) :
  cannot open the connection
Error during wrapup: cannot open the connection
```
If you manually create the output folder ahead of time you get this.
```
2017-05-31 09:13:18 SEVERE [fn] :
   Start year of ensemble should come after the start.date of the run
Error in logger.severe("Start year of ensemble should come after the start.date of the run") :
  Start year of ensemble should come after the start.date of the run
> # Write pecan.CHECKED.xml
> PEcAn.settings::write.settings(settings, outputfile = "pecan.CHECKED.xml")
[1] "/data/Model_Output/fates_pecan_runs/new_test_1/pecan.CHECKED.xml"
```

If you correct the date mismatch you get a run that will follow through to completion

## Description

It seems we should stop and provide the error that the dates don't match before moving on so that the error is more descriptive?

**Comment by serbinsh** [comment]
Such as 

```
nohup Rscript workflow.R > workflow.log 2>&1 &

```

**Comment by infotroph** [comment]
I think I've tracked down what's happening here, and possibly in some of our other "workflow continues after severe" issues: The workflow's error handler calls `status.end` then `kill.tunnel` then `q`, which means any error in `status.end` or `kill.tunnel` causes the error handler to stop (with message "error during wrapup") before it calls `q`... and therefore the whole workflow will think the error has been handled and try to continue execution.

In this case the proximal error is that `status.end` tries to write to a STATUS file in `/data/Model_Output/fates_pecan_runs/new_test_2/` but the directory hasn't been created yet. That's a bug itself (Maybe two: if we're calling `status.end` now, shouldn't `status.start` have noticed the same problem earlier?), but I think we also need to revise the error handler so that errors in earlier steps *can't* prevent it from calling `q`. One possible approach:

```
options(error = quote({
  tryCatch(
    expr = {
      PEcAn.utils::status.end("ERROR")
      PEcAn.remote::kill.tunnel(settings)},
    finally = if (!interactive()) {
      q(status = 1)
    })
}))
```

**Comment by serbinsh** [comment]
Nice work @infotroph!!!

**Comment by infotroph** [comment]
I'm not 100% sure the output-not-created issue that @serbinsh was originally reporting got resolved, but I'll close this hoping the improved error handling has made it at least easier to detect and correct the problem.
