### ISSUE TITLE
FLUX COURSE 2017

### ISSUE THREAD

**Issue by tonygardella** [PecanProject/pecan#1439]
Epic issue to organize features/tutorials/documentation we need for Fluxcourse

## Description
THREDDS - Rob
Benchmarking verification -Betsy
PDA - Istem
SDA - Raiho
Demo 01 and 02 - Tony 
Visualization Tutorial - Tess
Data Assimilation by hand tutorial - Tess
Benchmarking Tutorials/documentation - Betsy

**Comment by ankurdesai** [comment]
For record, here is the idea James is thinking of that could be built off his work that he emailed to me yesterday:
I've already created multiple, well documented scripts (it's a habit at this point) that could be used to do all of this within a half-day. That's assuming that we give them access to the linear regression models on a public server. The gen.subdaily.models() step (which is step 1 of 2) will take about a day to process. So perhaps that's something we could g ahead of time and give everyone access to the location their stored at? Here's my idea for the template workflow where everything is done in Rstudio:

1) Generate linear regression models ahead of time for Niwot Ridge for example
2) Download a dataset of their choice at Niwot Ridge lat/lon (I recommend MACA)
2) Have students use the predict.subdaily.workflow() to temporally downscale a dataset of their choice (For each year it takes about 1 hour 15 minutes to run, adding ensembles doesn't slow it down too much, just takes up more local memory but I haven't had any issues with that at all)
3)  Eat Lunch/Break while everything is running
4) Run sipnet using XML/pecan.workflow I've hacked and specify met$path to be the downscaled dataset
5) To show why resolution is important, they can use the scripts I've developed to temporally upscale Niwot Ridge FLUXNET to time steps of their choice, convert these to sipnet.clim's, run sipnet using my XML/pecan.workflow, and make a plot similar to what I showed you earlier.

It depends how automated you want this to be, but including downloading/downscaling time, this could take as little as 2.5 hours. It might be a nice exercise to perform around lunch. The talk you gave last year would transition nicely to this type of stuff. I'll make sure to keep documenting the hell out of my scripts and make sure they can be easily functionalized. I can upload them to my personal Github, or if you wanted to set up a FluxCourse Github I can upload them to there.

**Comment by mdietze** [comment]
I'm really worried about steps 2 and 3 above. They're going to eat up a lot of time and bandwidth (these files seem to be huge) and I'm not sure what the actual educational objective is in having them run the downscaling themselves vs. having the downscaling pre-run and on the next release ahead of time. I also don't follow the math -- if it takes 1.25 hr to predict 1 yr of met, the met for an interesting forecast (e.g. multidecadal) would take days to run.  I think there's going to be enough 'waiting' time in doing the ensemble model runs.  

I like option 6, of seeing how resolution impacts. I could also see another option of running with just met ensemble, just parameter ensemble, and both parameter and met ensemble to look at (A) their relative magnitude/importance and (B) if there's any interaction -- is the param X met ensemble more or less variable that you'd expect from just combining the variance from each separately.  I could also see an ambitious group doing runs that looked at the relative importance of different met variables --- for example, you could make a copy of the met ensemble and then set one variable (or all variables except 1) to it's ensemble mean.  I'd really love to see us doing this sooner (rather than later) in a multi-model setting to figure out the relative importance of different met drivers and how that compares to the importance of the different parameters.

**Comment by ankurdesai** [comment]
I like this idea of having an ensemble of met runs (provide ensemble met), ensemble of parameter runs, run spinet through each, and compare variance of separate and combined. That seems straightforward and doable.
