### ISSUE TITLE
Add `harddisk_id` column to machines table

### ISSUE THREAD

**Issue by ashiklom** [PecanProject/pecan#1472]
This came up in our lab group discussion.

Currently, we have an issue whereby three of our PEcAn machines share the same physical storage, which leads to either duplication in the database _or_ falsely missing files (e.g. a file that is present on pecan2 can show up as absent on pecan1 even though the file is actually there).

I propose that we add a `harddisk_id` or `physicalstorage_id` (etc...) to the machines table, and potentially add another `harddisks` or `physical_storage` table that stores paths to eliminate this issue. Ideally, the `dbfiles` table would link to the storage table rather than the machines table, but this seems like it could be a major backwards-incompatible change so there may be similar but less intrusive ways to solve the same problem.

Thoughts? @robkooper @dlebauer @mdietze

**Comment by dlebauer** [comment]
Isn't there a single identity for the machine that hosts the physical storage? Is there a way that the PEcAn machines that mount the storage machine directly could recognize the identity of the storage machine as being mounted locally?

**Comment by mdietze** [comment]
@dlebauer we're open to other ideas, but I'm not sure I follow what you're suggesting. Every idea we had prior to this would have caused the issues Alexey discussed earlier or would require ugly machine-specific hacks in the code. Any way of recognizing mounts would have to be OS independent, which seems unlikely

**Comment by robkooper** [comment]
I think what david is saying is that all 3 machines could share the same virtual name, pecan.bu.edu.  In that case all 3 machines (and more in the future) will pretend to be called pecan.bu.edu. This can be done by changing the fqdn in config.php. We need to make an update to the R code that collect the fqdn (https://github.com/PecanProject/pecan/blob/develop/utils/R/fqdn.R). 

Maybe have a variable called PECAN_HOST that can be set to be the hostname that would override the hostname retrieved using fqdn.

**Comment by dlebauer** [comment]
@mdietze I didn't have a specific implementation in mind, was just trying to suggest some possible avenues for finding a solution. @robkooper 's suggestion makes sense.

**Comment by ashiklom** [comment]
I like @dlebauer and @robkooper 's idea of a virtual name -- definitely seems much easier to implement than what I suggested.

One potential pitfall is if the different machines have the same storage but are running different software versions. For instance, if pecan1 has an older version of gcc than pecan2 and therefore a different executable for ED, how would that be handled? Is that a real problem? Or could that just be resolved by naming model executables by different names (e.g. have `ED2.pecan1` and `ED2.pecan2` exist on the same machine)?

**Comment by mdietze** [comment]
I think it's important to acknowledge that there are at least 2 different parts of this suggestion.

The first, how the hostname/machinename is handled in the php code. In that regard, having those specified sensibly in the config.php is fairly simple. Either one just has to set ```$fqdn``` to the assumed common machine name, or if there are places where we need different host/machine names, leave ```$fqdn=exec('hostname -f');``` and set ```$bety_machinename = $fqdn``` as the default with a clear comment to set that otherwise if need be. In either case, the machinename needs to be written into the pecan.xml since it won't always equal fqdn.

The second part of this suggestion is how to handle this within the PEcAn R code, which may require a lot of grepping through the code to check the logic of how machine.id and fqdn are used.

A couple other things on the to-do would be updating the machine id's of a lot of dbfile records (and resolving conflicts) and moving all files that are not on the shared space (e.g. /home).

That said, I agree with @ashiklom that this seems to be the best idea suggested yet.

**Comment by robkooper** [comment]
Closing this issue for now since there seems to be a reasonable solution. If multiple systems shares the same database and filesystem for the data, it should be treated as if it is one larger virtual system.
