### ISSUE TITLE
Conflicting versions of R required for make dependencies on remote

### ISSUE THREAD

**Issue by mccabete** [PecanProject/pecan#1548]
When on Geo remote, I prevent an error thrown by issue #1547 by running R/3.4.1. However, there are some packages used in make that aren't available for R/3.4.1, or cannot be automatically updated during the make process.

Packages that threw an error and exited make:
'magic'
'iterators' - Built before R/3.0.0
foreach - Built before R/3.0.0
'taxize'

I also received this warning: 
```
Installed Rcpp (0.12.12) different from Rcpp used to build dplyr (0.12.10).
Please reinstall dplyr to avoid random crashes or undefined behavior.
````

## Workaround
Running ```install.packages()``` in R in order ('iterators' -> "foreach" -> 'taxize' -> 'magic')  worked just fine.

**Comment by mccabete** [comment]
@ashiklom  Are issues like these actually solvable or are they just dependent on the quirks of the remote?

**Comment by ashiklom** [comment]
I think the issue here is jumping between R versions pointing to the same library. By default, R solves this problem by using a different R library for every major version (e.g. `~/R/library/3.4`), but we tend to override this by always setting our library to something like `~/R/library`.

One possible solution is to run `update.packages(ask = FALSE)` and let R automatically update all the currently installed packages. An even more robust solution is to just force a reinstall of every package. You can write a script like this and then just `qsub` it on `geo`.

```r
pkg_matrix <- installed.packages()
pkg_vec <- pkg_matrix[,"Package"]
install.packages(pkg_vec)
```

This will automatically bring every package to the most up-to-date version, and should also resolve the `Rcpp` issue in that warning.

There is almost definitely no good way to resolve these issues with `make`. Switching major R versions should always be done with caution, and it should be up to the user to make sure that the migration happens smoothly.
