### ISSUE TITLE
Remove this from config.php?

### ISSUE THREAD

**Issue by serbinsh** [PecanProject/pecan#1704]
https://github.com/PecanProject/pecan/blob/dde43144d5edae231fc6156843d60a095558824c/web/config.example.php#L114

**Comment by serbinsh** [comment]
@robkooper Basically, it seems this local sync test code should not be here correct?

**Comment by mdietze** [comment]
@serbinsh I'd agree that the sync settings may not need to be in your local config.php, and that you'd definitely have to change them in your local, but it's good to have an example of every config in the example otherwise people won't know what tags are valid. @tonygardella that reminds me, we should open an issue to make sure we document how to configure config.php similar to how we document how to configure pecan.xml

**Comment by robkooper** [comment]
In this case I think documentation is missing which would help. Having the default a blank and the server pointing to a not real IP is a good thing, since this feature is not ready for primetime yet.

**Comment by serbinsh** [comment]
@mdietze OK, thats fine since it is a new feature being added in....however when I raised this on gitter you mentioned that the config.php should not have had that in there ....so i guess I mis understood

**Comment by mdietze** [comment]
My point was that we should only commit changes to config.example.php, and if anyone committed their local config.php that was a mistake. Sorry for the miscommunication.

**Comment by serbinsh** [comment]
Can this be closed? This was created from a mis-understanding of mine about a new feature.  Or we can leave this here until it is documented.
