### ISSUE TITLE
do_conversions() overwrites all file-paths with local file-path

### ISSUE THREAD

**Issue by mccabete** [PecanProject/pecan#1770]
If you provide custom met by registering it to bety, and have more than one associated file (ie, one local, one remote), then the do_conversions() step will overwrite that file-path with the local file path. This causes failures on remote runs. 

## Description
This happens as a result of a commented out section [here](https://github.com/PecanProject/pecan/blob/a727c3aa6f21bec5636734877cf88041b46b9172/modules/data.atmosphere/R/met.process.R#L263).

**Comment by mccabete** [comment]
@tonygardella @mdietze  For now my plan was to uncomment the code in a private branch.

**Comment by tonygardella** [comment]
So it looks like during the staging process it understands that none of the met stages need to be run so it goes to t to get the input id of model specific files it needs. It then  grabs the one on the host machine rather than the machine where the run is done on.  I believe the fix would be to check the pecan.xml for the correct machine that the file must be on and then use that id in the line you mention.

**Comment by infotroph** [comment]
Fixed by #1822
