### ISSUE TITLE
Update Project info (readme, website, wiki)

### ISSUE THREAD

**Issue by dlebauer** [PecanProject/pecan#228]
- Remove background from wiki
- point to website, wiki from Readme
- .... ? canonical place for background

**Comment by mdietze** [comment]
Rob, I'm going to try and spend a good chunk of time next week updating the User's Guide on the wiki (in prep for NACP) plus the instructions for adding a model (because the Notre Dame folk will be visiting to add LINKAGES to PEcAn). If you have anything pending on this issue it'd be great if you could get it in soonish so we don't conflict with each other. Otherwise, let's keep HipChat open next week so we can discuss as needed.

**Comment by tonygardella** [comment]
Wiki has been migrated to gitbook with big help from @bcow . Links and details will be posted once we figure out how to manage things correctly.

**Comment by tonygardella** [comment]
Gitbook is up: https://www.gitbook.com/book/pecan/pecan-documentation/details
[ ] - PecanProject/pecan.book#1 - Need to clean up broken links before starting revision
