### ISSUE TITLE
Replace stats::aggregate() with dplyr::summarize()

### ISSUE THREAD

**Issue by rahul799** [PecanProject/pecan#2505]
When working with an analysis system (such as R), there are usually good reasons to prefer using functions from the “**base**” system over using functions from extension packages. However, R-stat code tends to have a habit of [dropping attributes](https://www.r-bloggers.com/dont-use-statsaggregate/) when it can. 

Using `dplyr::summarize()` solves this problem & must be used instead of `stats::aggregate()`

**Comment by infotroph** [comment]
I have a few competing thoughts here: 

* `stats::aggregate` certainly has its share of gotchas, many of which `dplyr::summarize` handles more uniformly/intuitively, and I agree that any given aggregate->summarize change can be done without worrying too much about the extension load. Possible exception: Packages that don't yet import any part of the Tidyverse, in which we should worry about it the correct amount but still not too much..
* Handling attributes correctly always requires some care -- including in dplyr, at least until recently (see the messy trail of issues referenced from https://github.com/tidyverse/dplyr/issues/5132), so I lean toward thinking of attribute preservation as something that should be tested for with specific use cases in mind rather than treating it as necessary across the board.
* Are there specific places in the workflow where this is a problem? As far as I know most of the data structures generated inside of PEcAn don't add extra attributes in the first place, but if there are places external user data is getting mangled then we definitely want to know and fix it.

**Comment by rahul799** [comment]
No, it is not causing any problem yet & what you have mentioned in the second point is enough to close this issue.
