### ISSUE TITLE
Dealing with stale issues

### ISSUE THREAD

**Issue by rahul799** [PecanProject/pecan#2556]
## Description

There are **427 open issues**, where many are opened **since 2014** .
Having stale issues hanging around the repository can be a significant detriment. It makes it harder to find the important ones that we want to focus on.

## Proposed Solution

Using a [stale action workflow ](https://github.com/marketplace/actions/close-stale-issues)can be the right choice.

When it runs, it will run the stale action which will look at the issues and pull requests in the repository and find the ones that haven't had any action for a few months. It will then post a message in the issue and add a label indicating that the issue is stale. If that issue stays stale for another week, it's closed.

**Comment by ayushprd** [comment]
Nice idea. Just a question, is it possible to have issues with certain labels be exempted from this action? other than manually removing the stale labels. For instance, many issues labelled as documentation or datasets might be required even if they are old.

**Comment by infotroph** [comment]
Disclaimer: This is my own opinion and I'm definitely not speaking for the whole team.

The challenge of finding relevant issues is definitely real, and I'm sure many of our old issues *could* be summarily closed, but I'm hesitant to close anything automatically just because it's old or inactive. I lean toward thinking stale action workflows are a bad idea in general (I can rant elsewhere about why 😉), and I feel pretty strongly that it's the wrong model for this project in particular:

* Lots of contributors who only occasionally have time to code -> lots of long pauses that don't actually mean a project is abandoned
* Corners of the codebase that aren't exercised very often -> hard to tell whether a bug is a weird one-off or an ongoing problem; often "let's leave this open for a while and see if anyone else can reproduce it" is the easiest way forward
* Our releases are far enough apart that it's hard to pick a definition of "stale" that won't catch something punted from one release to the next
* Many modules with only one or a couple of codeowners -> many issues are de facto one person's problem -> long backlogs for non-critical issues
* The product is a scientific workflow with high priorities on reliability, reproducibility, and transparency. If a bug exists, we'd much rather have a public record of it with a clear indication it isn't resolved yet (i.e. an issue marked as open), even when feels embarrassing to see how many there are.

**Comment by rahul799** [comment]
These points are crucial, which I didn't think of earlier. Thankyou @infotroph for bringing these into the light.

**Comment by dlebauer** [comment]
full list of options in https://github.com/actions/stale/blob/master/action.yml

Some relevant to this discussion:
* specify tags to exempt issues from being marked stale https://github.com/actions/stale/blob/master/action.yml#L27
* prevent closing by setting the days-before-close to 100000 (will give us to the year 2294)

**Comment by infotroph** [comment]
That's a good point: *marking* as stale doesn't have to mean *closing* as stale, and I think at least 3 of my 5 points above only apply if the issue get autoclosed.
