### ISSUE TITLE
Deciding the SMAP layers to download from AppEEARS

### ISSUE THREAD

**Issue by ayushprd** [PecanProject/pecan#2654]
## Description

For the remote data module, @istfer  and I decided to download all the layers/bands for a requested product. This is causing a unique problem while downloading SMAP data from AppEEARS, all of the SMAP products available have more than 40 layers individually, so when the AOI type is a Polygon and time period extends over six months the API does not allow to download all the layers and asks to reduce the data request further. This problem does not occur when the AOI is of Point type.

Currently, this problem only happens for SMAP as other products on AppEEARS don't have these many layers
## Possible Implementation

I think if we make an exception for SMAP and only download the required layers (less than 25) we will not have to face the above problem.
@mdietze @julbateman @kzarada @serbinsh could you all please suggest which layers should we download?

I think the product `SPL3SMP_E` matches closest with the description Juliette and Katie provided us.

SMAP products available on AppEEARS: https://lpdaacsvc.cr.usgs.gov/appeears/products

**Comment by mdietze** [comment]
We got this bit of feedback from Dan Gianotti:

My vote is for the level 3 (L3) products. SMAP orbits multiple times a day. L1 is brightness temperatures from individual orbits. L2 is the L1 data processed from brightness temperature into soil moisture through a retrieval algorithm (there are a few, but the “baseline” or “single channel” algorithm (SCA) is the default. L2 data is still stored swath-by-swath, that is, there are multiple overpasses per day and each is stored separately. The only thing that happens from L2 to L3 is that the soil moisture data are “composited” into a single daily file.  Overpasses are (in theory, and to very good approximation) at 6am and 6pm local time. The 6pm data are not worth using unless you really know what you’re doing.  Use the 6am (morning) overpasses. For almost all data, the observations come from just one overpass each day. For locations poleward of 65 degrees (N or S), the swaths overlap, and so the L3 compositing has to somehow determine what soil moisture value to assign. The baseline algorithm just uses the values closest to 6am/pm (since at the poles there is real deviation from the local time from one swath to another). So, it is generally easier to deal with the L3 daily data, which will give a single 6am soil moisture value for each observed pixel. Near the poles, the observations are daily (more than daily, as mentioned, but composited to daily). Near the equator, the data come ~every 3 days. And closer to every 2 days in the midlatitudes. The exact revisit time follows a funny pattern that repeats exactly for every location of earth every 8 days, so a flux tower might have a pattern of observations (o) and missing data (x) that looks like oxxoxoxo and repeats like that over and over again every 8 days (this mostly only matters when you are doing spatial analyses – sometimes you can get sampling frequency patterns if you do data averaging on, say, 5-day time scales).
 
The spatial resolution of the radiometer is on the order of 25 km, but is gridded at a choice of a) 36 km, or b) 9 km (the “enhanced” products). I usually work with the 9 km data, and don’t think there is much reason to prefer the 36 km data unless you are really getting into spatial statistics and are worried about artifacts from their algorithm.  There was supposed to be a 3 km product (the “Active/Passive” AP product), but the radar broke shortly after launch. This has been replaced with a 3 km product that uses active radar from one of the Sentinel satellites, but they can only create this when SMAP and Sentinel are basically crossing over each other, so you get revisit times on the order of 2-4 weeks (probably not what you want for a site-level study).

**Comment by julbateman** [comment]
@ayushprd Based on what Dan Gianotti said, I would agree that the SPL3SMP_E is the best match

**Comment by ayushprd** [comment]
Thanks, @mdietze @julbateman I was wondering if you all could further narrow down the required layers from `SPL3SMP_E` 
![Screenshot from 2020-07-14 19-38-12](https://user-images.githubusercontent.com/11568631/87437511-0ab89e80-c60c-11ea-83b3-9f0575179690.png)
Right now If you all don't exactly know which layers you would need then no problem I'll simply select the first 25 layers for now. You can later change it in the code.

**Comment by julbateman** [comment]
@ayushprd I'm not sure what may be needed in the future, so I think it sounds like a good idea to select the first 25 layers (from the AM passes), and then we can change it later if necessary!
