### ISSUE TITLE
model2netcdf.ED2 not processing ensemble runs; all runs are ensemble runs

### ISSUE THREAD

**Issue by mccabete** [PecanProject/pecan#2689]
### Bug Description

When I run model2netcdf.ED2 on a single-ensemble run, model2netcdf.ED2 trows the warning 
```
2020-09-02 18:20:32 INFO   [model2netCDF_including_ed2_names.R#91: PEcAn.logger::logger.info] : 
   This is an ensemble run.  Not processing anything.
```
and returns `NULL`.  I think all model runs are ensemble runs now, even when the ensemble = 1, so model2netcdf.ED2 isn't running on newly ran ED2 files. 

### To Reproduce
Run model2netcdf.ED2() on an existing run with ED2 .h5 files. 

## Additional context

The warning is thrown [here](https://github.com/PecanProject/pecan/blob/develop/models/ed/R/model2netcdf.ED2.R#L91). Looks like based on [these-comments](https://github.com/PecanProject/pecan/blob/develop/models/ed/R/model2netcdf.ED2.R#L71), that this was supposed to be a temporary check that prevented errors when different ensemble members were different lengths. Unclear if that would still be an issue if the `ensemble` check were deprecated.

**Comment by mccabete** [comment]
@istfer I think you implemented this check [in this commit](https://github.com/PecanProject/pecan/commit/6d9eb3e35b1aee564c6c03284597c08ec08229fb) Do you happen to remember the nature of the errors it was preventing?

**Comment by istfer** [comment]
Hi @mccabete sure I remember. But this check is evaluated only if `max(year_check) < end_year`. So if running model2netcdf.ED2() on an existing ED2 run with all the files that are all supposed to exist, you shouldn't normally hit this, if you hit it, it is probably because your run partially failed.

The error this was preventing goes like this:
Suppose I give an ensemble run of 3 for years 2010-2015. You know how ED2 can fail for some years or for some parameter combinations but not for others. So let's say one ensemble run failed after 2012: run1 and run2 produces output files 2010.h5 to 2015.h5, but run3 only has 2010.h5 and 2011.h5. Our model2netcdf has no problem converting these to .nc files, but the problem comes later on in the ensemble functions [downstream](https://github.com/PecanProject/pecan/blob/develop/modules/uncertainty/R/run.ensemble.analysis.R#L268) where it tries to fill the matrix with a shorter timeseries, I don't remember the exact error but you would probably get something like `number of items to replace is not a multiple of replacement length` error.

This code bit skips processing the (partially) failed run altogether so that downstream it doesn't hit this error, because unlike partially failed runs, ensemble functions are able to handle [completely failed runs](https://github.com/PecanProject/pecan/blob/develop/modules/uncertainty/R/run.ensemble.analysis.R#L256). This way if one or more ED2 ensemble runs fail partially it still doesn't break the workflow.

This is not an issue for sensitivity or PDA runs (i.e. not all model runs are ensemble runs) because those functions handle run outputs differently.

There could have been different ways to avoid this error, e.g. changing the ensemble functions, or filling partial fails with all NAs in met2model.ED2(). I went with this because it was the path of least resistance at the time.

**Comment by mccabete** [comment]
I hadn't noticed the `max(year_check) < end_year`  bit.  My bug is probably a product of my script not setting end_year correctly, or a partially failed run. I'll resolve this issue. Thanks for the context Istem!
