### ISSUE TITLE
`PEcAn.utils::download.file` masks `utils::download.file`.  Change name?

### ISSUE THREAD

**Issue by Aariq** [PecanProject/pecan#2957]
https://github.com/PecanProject/pecan/blob/cd3e4c2dc1739b4165574dd1200f73886d80af9a/base/utils/R/utils.R#L647

This might be annoying to users who find base R's `download.file()` unexpectedly working differently and with different arguments.  Consider renaming to `download_file()`?

**Comment by infotroph** [comment]
I support renaming it, or possibly retiring it entirely -- I think `utils::download.file` has gained some functionality in recent R releases that *may* (though I have not tested) let it handle firewalls natively.

As a historical note, I believe the original design was that `PEcan.utils::download.file` was supposed to intentionally mask `utils::download.file`, but to behave identically for users who didn't configure otherwise. But (1) it doesn't actually behave identically (our version ignores `method` for non-ftp downloads), and (2) as we become more consistent about using namespaces throughout PEcAn it becomes less and less likely that the `PEcAn.utils` copy will mask the base one effectively enough to be useful for those who did want it.

**Comment by Its-Maniaco** [comment]
@Aariq @infotroph Is this issue up for grabs?

**Comment by moki1202** [comment]
@infotroph @Aariq is this issue still up for grabs?
