### ISSUE TITLE
Add list of models to MOTD

### ISSUE THREAD

**Issue by robkooper** [PecanProject/pecan#338]
Currently on ED and SIPNET listed, missing BioCro, Dalec and Linkages.

**Comment by mdietze** [comment]
What's MOTD?

**Comment by robkooper** [comment]
MOTD is message of the day. When you login through SSH on the machine you will see it and it shows URL's to PEcAn, BETY, ED and SIPNET.

We should probably update the home page of the VM and show those URL's as well.

**Comment by mdietze** [comment]
Probably simpler to drop the model-specific URLs and just give the link to the wiki page that lists the current models:

https://github.com/PecanProject/pecan/wiki/Getting-started#supported-models

Or just give the link to the whole “Getting started” section of the wiki, since that includes a ton of info that new users should be looking at.

On Jan 26, 2015, at 3:25 PM, Rob Kooper <notifications@github.com<mailto:notifications@github.com>> wrote:


MOTD is message of the day. When you login through SSH on the machine you will see it and it shows URL's to PEcAn, BETY, ED and SIPNET.

We should probably update the home page of the VM and show those URL's as well.

**Comment by robkooper** [comment]
Updated wiki, will add link to list of models on webpage in next release.
