### ISSUE TITLE
Link documentation to pecanproject.org

### ISSUE THREAD

**Issue by dlebauer** [PecanProject/pecan#361]
A user suggested 

> add a tab at http://pecanproject.github.io/ labeled 'documentation' that points to
github.com/PecanProject/pecan/wiki 

This would be a good first step, but another idea would be to consider compiling the documentation into a set of pages within the website. This can be done using jekyll, but is beyond my level of expertise.

**Comment by mdietze** [comment]
Tab added.

I disagree that adding the documentation directly to the website is a good idea -- this is an extra step that just results in having the same information in two places, which is confusing and will result in the two inevitably being out of sync. Better to have this all in one place, and the wiki is better since it's right there with the bug reports, development timeline, and code.

**Comment by dlebauer** [comment]
Generating web pages could be automated. My primary concern is that the current wiki is getting so big that the navigation becomes daunting. In addition, navigation is lost when scrolling down to the bottom of our very long pages.

Also, I am less concerned about the perspective of a developer as from the perspective of a new user. 

But my guess is that before long GitHub or some third party will solve this.

**Comment by mdietze** [comment]
Even if the webpages are generated automatically, they're the same pages. I don't really understand what you mean when you say "navigation is lost", but if the pages are too long this would need to be fixed within the wiki. Others may disagree with me, but I feel the advantages of working within a wiki (simple syntax, updatable by the whole group) outweigh the costs (aethetics)
