### ISSUE TITLE
Period in package name (PEcAn.rtm) conflicts with Rcpp compilation

### ISSUE THREAD

**Issue by blowfish711** [PecanProject/pecan#391]
In developing the RTM package, I had to change the package name from PEcAn.rtm to PEcAnrtm (no period) to allow it to compile. The issue is that when Rcpp compiles its libraries for export to the package namespace, it labels them as `PACKAGENAME_function(...)`, but since it's C code, it doesn't accept PACKAGENAMEs with periods in them (namely, `PEcAn.rtm`)

Rcpp is incredible for code optimization because the resulting C++ code is very R-like (`rnorm`/`dnorm` calls, vectorization, `apply` functions etc.), but still blazingly fast (in fact, even faster than native C++ because of a lot of underlying optimizaiton). I for one would like to use it heavily in all my work that involves numerical heavylifting in R, but this limits me from using it in any package that has a dot in the name. If we're OK changing package names, we can just do that, but I wanted to call everyone's attention to it first.

The developer has explicitly pointed out that you can't do this, unless we do manual comiplation, which is a lot harder (but I guess a possibility): http://stackoverflow.com/questions/20720796/package-compilation-fails-when-package-name-contain-a-dot-and-rcpp-function.

**Comment by dlebauer** [comment]
What a headache! 

I think the simplest solution would be PEcAnRTM. But such inconsistencies are irksome. While we are at it, the mixed caps of PEcAn is quite beautiful in print, but cumbersome in code.

I'd support in concept switching our dot convention to underscores. And while we are at it, pushing all instances of the string "PEcAn" to pecan. My pinkie has had it with the mixed caps!

If we are doing such a thing, changing PEcAn.DB to pecan_database, PEcAn.MA to pecan_metaanalysis, ane PEcAn.rtm to pecan_radiativetransfer. otherwise pecanDB, pecanMA, pecanRTM.

And any functions beginning in `start./plot./etc` that can be confused with S3 methods (#380)

But **don't** try this (it will corrupt git)

```sh
 find . -type f | xargs sed -i 's/PEcAn\./pecan_/g'
```

If we do such a thing as rename packages ... that would justify [bumping to v3](http://semver.org/) and would be a headache.

**Comment by blowfish711** [comment]
Thanks for the quick reply, Dave! My understanding is that R does not allow underscores in package names, so I would vote for something like pecanRTM. lowercaseCapital is a common convention in a lot of things anyway.

**Comment by dlebauer** [comment]
OK. For now, go with PEcAnRTM. I've created #392 to track global changes that would introduce backward-incompatibility.

I am going to go ahead and close this. But if you want to introduce some conventions for using Rcpp in particular (that are PEcAn-specific, or are otherwise not in / different from Hadley's book chapter on Rcpp) please document [them in the wiki] (https://github.com/PecanProject/pecan/wiki/Development#r-development). Would be great if you could give a quick overview of using Rcpp with screen-sharing on at a future PEcAn meeting.

I'll go ahead and put in a pull request that will #393 that will close this issue once merged by @PecanProject/owners
