### ISSUE TITLE
Time zone unit standards and conversions in met conversion scripts?

### ISSUE THREAD

**Issue by dlebauer** [PecanProject/pecan#459]
Have we decided on conventions for reference dates and/or time zones for met inputs?

### Units

The [wiki](https://github.com/PecanProject/pecan/wiki/Adding-an-Input-Converter#the-variable-names-should-be-standard_name) suggests a common time dimensio nof `1700-01-01 00:00:00 UTC`. 

However, I am not sure where this has been implemented. Did we decide to allow the start date and time zone to be flexible? How must it be specified?

### Conversion to local time

Is there a standard way of converting from either UTC to local? 

I would suggest converting to solar noon (rather than to a particular time zone. This could be as easy as:

* solar noon = UTC + 24 * latitude / 360

This uses 'mean solar time', i.e. does not account for the [equation of time](http://en.wikipedia.org/wiki/Equation_of_time) that causes +/- 15 min oscillation in solar noon over the course of the year.

It also does not account for site-level met data collected in a particular time zone. Getting the value right within an hour is a good first step.

**Comment by ankurdesai** [comment]
The nice thing about the time dimension + udunits in netcdf is that as long as either base_time is defined or time has an attribute that describes the start time (i.e., Days since 2003-01-01 00:00:00 UTC), then working with the time unit, whether it is from 1700 or from the year of the file if trivial. I like using a base time that is closer to the start of the time series in the file, if only to make the time variable more human readable, at the expense of more lines of code for extracting the time unit (which perhaps we should generalize into a helper function) 

We could decide to adopt the 1700 to make all code assume that, but that would sometimes require rewriting netcdf files.

Generally local time refers to the time zone (usually standard time) not solar time. I'm not sure why solar time would be useful except in analysis. Generally just noted in the netcdf attributes by the time zone offset (e.g., Days since 2003-01-01 00:00:00 UTC-6 (I think, or it might be just -6)). Meteorologists put everything in UTC when they can. I don't know how to identify solar time in netcdf, except to define a specific timezone.

There must be some time functions in R for adding/subtracting hours to a datetime object.

**Comment by mdietze** [comment]
On https://github.com/PecanProject/pecan/wiki/Adding-an-Input-Converter it says

"Dates in the database should be datatime (preferably with timezone), and datetime passed around in PEcAn should be of type POSIXlt."

I agree with Ankur that solar time is not useful. If a data set is provided in local time that will very often be different from solar time, so if anything's going to be converted to a standard time it should be UTC. Also regional-scale data sets will span multiple time zones so there's no single unambiguous 'local' time. Conversions within the model-specific convert functions are totally up to an individual model and don't need to follow any PEcAn standards.
