### ISSUE TITLE
Add additional tags to pecan xml for ED2 model

### ISSUE THREAD

**Issue by serbinsh** [PecanProject/pecan#505]
@mdietze @robkooper @dlebauer 

I would like to add additional tags to the ED2 specific options for the PEcAn xml file we run with the PEcAn workflow.  Here you can find the current ED2 specific options:

https://github.com/PecanProject/pecan/wiki/ED2-Configuration

However there are a few other ED2IN options I would like to be able to tweak using the XML during a run.  Here are a list of the options I would like to include as optional:

In case we want to tweak integration /fast flux times
NL%DTLSM 
NL%RADFRQ

In case we want to include additional, "advanced user" outputs for model eval QA/QC
NL%IFOUTPUT
NL%IDOUTPUT
NL%IMOUTPUT
NL%IQOUTPUT
NL%ISOUTPUT

Same with these
NL%IADD_SITE_MEANS
NL%IADD_PATCH_MEANS
NL%IADD_COHORT_MEANS

Options to tweak soil properties (higher short-term priority)
NL%NZG
NL%NZS

NL%NSLCON

NL%ISOILCOL

NL%SLXCLAY
NL%SLXSAND

NL%SLZ
NL%SLMSTR

Other advanced options
NL%ISOILBC

NL%INTEGRATION_SCHEME

NL%IBRANCH_THERMO

NL%IPHYSIOL

NL%IALLOM

NL%REPRO_SCHEME

NL%CROWN_MOD

NL%H2O_PLANT_LIM

NL%IDDMORT_SCHEME
NL%DDMORT_CONST
NL%CBR_SCHEME

NL%MAXSITE
NL%MAXPATCH
NL%MAXCOHORT
NL%MIN_SITE_AREA
NL%MIN_PATCH_AREA

NL%INITIAL_CO2

**Comment by mdietze** [comment]
@serbinsh we never intended for PEcAn to modify every option in a model, that's why we allow you to use a non-default template, in case you want to customize options and then just point the pecan.xml to that customized template. The main reason to add a variable to the PEcAn xml is if we want the capacity to automatically vary it / integrate over it in the sensitivity analysis, uncertainty analysis, or data assimilation. I don't think any of these meet that criteria.

With regards to soil texture / properties, those can already be set in the *.site and *.pss files and it has always been my intention to eventually connect soil databases to the writing of those files. It's just that at the moment the met has been the priority (Betsy), followed by the veg (Josh). If you want to take a stab at a soils workflow I'd be keen to talk.

**Comment by serbinsh** [comment]
@mdietze OK, got it.  I had the impression that since we were including the ED2IN templates with PEcAn that we were trying to make that fully auto, through the XML.

My concern was that the soil props, etc are currently set for what I have done in the past for US-WCr, which of course isn't universal.  As such, I thought it would be good that those could be customized for different sites/locations.  In the short term I am using custom ED2IN templates, as suggested.

I would like to discuss the database idea with you at some point.  Lets open that up next Monday afternoon.

Thanks!
Shawn

**Comment by mdietze** [comment]
@tonygardella I'm closing this issue but lets make sure that @serbinsh's request that we discuss soil databases gets on the agenda for some week this fall. See also issues #506 #229 and #350
