### ISSUE TITLE
Ability to set ensemble size in web interface.

### ISSUE THREAD

**Issue by ch1eroe1** [PecanProject/pecan#517]
Currently in the pecan.xml file the ensemble value is hard coded to the value of 1.  This will allow the user set the number of ensembles to run.

**Comment by dlebauer** [comment]
Are referring to ensemble size? Note that when size = 1, all parameters are
set to their median value. When size>1, parameter values are quasi-randomly
sampled, so the results of an ensemble with only a few samples may not give
useful results. Generally I use 500 samples for 10-20 parameters.

Have you committed the changes you are proposing?

**Comment by robkooper** [comment]
Yes, the goal is to let the user set the ensemble size (and later the sensitivity as well) from the web interface. With the ability to run jobs using qsub #498 the user can now create larger runs in the web interface of PEcAn.

**Comment by dlebauer** [comment]
@mdietze do you think we should provide sensible defaults or guidance to
users on selecting ensemble size?

**Comment by serbinsh** [comment]
@dlebauer I think that would be a good idea.  Also, I may want to set a max ensemble size override in so that a user doesn't submit hundreds and hundreds of jobs, possibly by mistake or other reasons, through the web interface that hog my server queue.  I get that some runs will require a lot of SA and ensemble members but my concern is a user unnecessarily taxing my cluster, especially if they are just learning PEcAn or testing. Does that make sense? 

I will likely also look into more clever queuing so that internal users get a higher priority then web-based runs.

**Comment by mdietze** [comment]
Default should be n=1. We should not set restrictions

**Comment by dlebauer** [comment]
@mdietze I didn't intend to suggest setting restrictions, but that we
provide guidance on choosing sensible values. We could provide a list of
sizes, when to use them, and how to evaluate that the size is large enough.
For example, n runs < k parameters is nonsensical. n = 100 was not
sufficient. And n > 1000 might be justified after analyzing a run of 500. I
think n has generally been 500 in published analyses. Has anyone used more?

**Comment by mdietze** [comment]
@dlebauer I know, @serbinsh was suggesting restriction not you. I agree that documentation and any mouse-over help should provide recommendations, but otherwise let's not clutter the design with lots of text. I'm not worried about people running nonsensically small ensembles and I'm not sure why everyone else is. If people run computationally ghastly ensembles on your server, maybe you should provide personal guidance. For the demo server I could see a restriction since that one is public. Or we could put a max in the PHP config so each server owner could restrict their own group (or choose not to)
