### ISSUE TITLE
Ensemble size and median

### ISSUE THREAD

**Issue by robkooper** [PecanProject/pecan#520]
How do we want to deal with ensemble size (especially small ones). If we pick an ensemble size of 1, we pick the median, if we pick 2 or more we use the halton function to pick the ensembles.

@ryankelly-uiuc @serbinsh can you fill this out.

related to #491, #517

**Comment by ryankelly-uiuc** [comment]
I would first say that we should at least keep the current special case, where requesting an ensemble of size 1 automatically runs the median of all param distributions. 

Second, small ensembles (but with n>1) are always going to be dangerous, but I've noticed they're especially so when using the halton sampling method (at least the implementation we're using). This is because with high dimensions (e.g. sampling 10-20 parameters), the first few samples are all on the low end. Hard to explain but easy to see:

    > library(randtoolbox)
    > halton(n=3, dim=9)
     [,1]      [,2] [,3]      [,4]       [,5]       [,6]       [,7]       [,8]       [,9]
    [1,] 0.50 0.3333333  0.2 0.1428571 0.09090909 0.07692308 0.05882353 0.05263158 0.04347826
    [2,] 0.25 0.6666667  0.4 0.2857143 0.18181818 0.15384615 0.11764706 0.10526316 0.08695652
    [3,] 0.75 0.1111111  0.6 0.4285714 0.27272727 0.23076923 0.17647059 0.15789474 0.13043478

Note that by parameter 4 all samples came from below the median, and the last parameters to be sampled are really coming from the tip of the lower tail. If you do this for dim=20 the last three params are sampled from below the 5th percentile. 

Obviously, the situation gets better if you request a bigger sample, but it gets worse as you increase dimension (sample more parameters).  E.g. for 10 parameters you can get away with about n=50 ensemble members, whereas for 20 you need around n=100 to get good coverage. 

I made a small change to my code that allows uniform random sampling to be used instead (the option is in there already, but can't really be turned on because of how `get.ensemble.samples()` is called). For small ensemble sizes I tend to think this is a better idea than using the halton sequence, which is clearly biased. I'll push the change soon along with some other stuff I'm working on.

**Comment by mdietze** [comment]
I believe there's already an issue about adding alternative samplers to the halton (random, lhc, sobol, etc)

**Comment by ryankelly-uiuc** [comment]
Indeed—gh-491. 

The issue that really came up in the call (at least initially) was whether or not to *always* include the median as an ensemble member, so that small ensembles had at least one member that wasn't way out in left field. I thought we may as well, whereas Toni was concerned it was a bad idea (because the median + a few shitty samples = still a shitty ensemble). I just want to keep the special n=1 case because it's handy for testing.

**Comment by mdietze** [comment]
Yes, we keep the special case that first is median.
