### ISSUE TITLE
Reduce resources used by ssh, rsync

### ISSUE THREAD

**Issue by dlebauer** [PecanProject/pecan#557]
PEcAn is using a lot of resources, including CPU

On the PEcAn host (ebi-forecast):

![image](https://cloud.githubusercontent.com/assets/464871/8562121/daa355fa-24f3-11e5-9e55-cb9cad646b7a.png)

Its not so bad on the HPC head node (roger.ncsa.illinois.edu), but only because another user is competing with me:

![image](https://cloud.githubusercontent.com/assets/464871/8562161/6539981e-24f4-11e5-94f8-37682ac775bf.png)

I propose to set nice / ionice to -1 on ssh / rsync calls in pecan, but am interested in other options (gftp?) that would help PEcAn use resources nicely.

Thoughts @yanliu-xsede, @robkooper ?

**Comment by robkooper** [comment]
when is this? is this during the actual transfer? transfers are expensive, especially since they are encrypted (ssh), not sure how much cheaper gftp is. Cheapest would be http but that would require a whole extra setup with firewall ports etc.

ionice might help, but honestly who cares. Both machines are 90% and more idle and the io wait is close to 0% so that is good as well.

**Comment by dlebauer** [comment]
>but honestly who cares

ebi-forecast seemed slow to load rstudio and I thought that might be an issue. The bigger issue would be if this were to crash betydb. I can tag this as wontfix and close it unless I find something intolerable.
