### ISSUE TITLE
Adding new variable to ED2IN template

### ISSUE THREAD

**Issue by Viskari** [PecanProject/pecan#595]
With the latest update of ED2, they added a new variable GROWTH_RESP_SCHEME to ED2IN. This causes a problem for pecan as if I add that to the ED2IN template for git version, it will no longer work with the older git versions of ED2.

So before I add it to the ED2IN template, I wanted to check if that is considered the correct approach here?

**Comment by mdietze** [comment]
Great question. We technically shouldn't be tagging 'development' branches of models in PEcAn, since the model is changing thus breaking provenance. Every git commit has a unique hex code, but tagging model versions with that would suck since they're not consecutive and unintuitive. In reality the ED community needs to start tagging more frequent releases and the PEcAn community needs to more frequently update the Models table as new versions within a ModelType are introduced.

In the short term I say add it to the ED2IN template and everyone else will have to update their ED code (which they need to do anyways).
