### ISSUE TITLE
Change PEcAnRTM to PEcAn.RTM

### ISSUE THREAD

**Issue by serbinsh** [PecanProject/pecan#604]
Chance description to PEcAn.RTM to be consistent with other PEcAn modules.  Make sure this change doesn't break code.

**Comment by dlebauer** [comment]
I believe you are just referring to the package name? If so, this _can be closed_ since names with periods are not allowed by Rcpp.

Per #391, #393, this name was used because Rcpp does not allow a period in the package name. 

One of the non-backward compatible changes proposed for v2.0 (#392) is to remove periods from package names (and to write "pecan" in lowercase to separate from package function).
