### ISSUE TITLE
Merge Shawn's R-FieldSpectra into PEcAnRTM

### ISSUE THREAD

**Issue by ashiklom** [PecanProject/pecan#624]
Would it be a good idea to merge the @serbinsh repository [R-FieldSpectra](https://github.com/serbinsh/R-FieldSpectra) into the RTM module? I think it would make sense in terms of enabling users to use a single package to process their field data and perform inversions. Moreover, if I'm going to be adding tools later for working with AVIRIS data, they could go hand in hand with the stuff Shawn's done here.

**Comment by dlebauer** [comment]
One thing to consider when determining the scope of a package is modularity. There are many times that it is preferable to keep a package independent. It is not always clear how to split things, and the units should be large enough to

 [Wilson et al 2014](http://journals.plos.org/plosbiology/article?id=10.1371/journal.pbio.1001745) make two related points at the scale of functions, but I think the idea scale up to packages. Imagine if PEcAn were still a single package (as it was until [v1.1](https://github.com/PecanProject/pecan/tree/690e3b7e2edb362c2cce79faa0094c7bddf87f6a))! 

> modularizing code allows people to remember its functionality as a single mental chunk, which in turn makes code easier to understand. Modularized code can also be more easily repurposed for other projects.

> First, a program should not require its readers to hold more than a handful of facts in memory at once (1a). Human working memory can hold only a handful of items at a time, where each item is either a single fact or a “chunk” aggregating several facts [33],[34], so programs should limit the total number of items to be remembered to accomplish a task. The primary way to accomplish this is to break programs up into easily understood functions, each of which conducts a single, easily understood, task. This serves to make each piece of the program easier to understand in the same way that breaking up a scientific paper using sections and paragraphs makes it easier to read.

**Comment by mdietze** [comment]
In terms of modularity and scope, I think it makes sense to combine and rename (since the scope would then be greater than just RTMs). Indeed, there's already been confusion among potential users between the two packages, and combining will probably make it easier to maintain. 

The other part of scope to consider is ecosys -- will that database be generating it's own dedicated R package? If not, would this package end up the de facto R interface?

My only counter arguments to merging:
* Is this what Shawn wants for his FieldSpectra package?
* We need to make sure the FORTRAN compilation is bomb-proof -- we don't want people who just want to use the field spec functions to not use the package because the RTMs are not compiling on their OS.

**Comment by serbinsh** [comment]
@mdietze and @ashiklom At this point, it probably makes sense to keep separate. I would want this code to significantly improved before merging with the RTM because there are various outstanding issues that I want to try and work through.  I have been trying to get a programming student from SBU to work on this but so far no luck.
