### ISSUE TITLE
PEcAn 1.4.3 local Ameriflux ED failure

### ISSUE THREAD

**Issue by tonygardella** [PecanProject/pecan#633]
The notes of the test were:

run dies with nonsense CO2: 3.80000E-10

**Comment by ankurdesai** [comment]
This looks like a umol CO2/mol air to mol CO2/mol air conversion happened twice. Since 3.8e-10 * 1e6 * 1e6 = 380 ppm, which is not nonsense. If expected unit is mol/mol, then it should be 3.8e-10 * 1e6 = .00038. There must be a pesky, extraneous 1x10^6 hiding somewhere, probably in met2model or alternatively in reading ameriflux. It could be a problem with the underlying source data...

**Comment by jam2767** [comment]
Here's what's happening. met2cf is taking umol/mol (ppm) * 1e6 instead of umol/mol / 1e6. This means values are 3.8e8 instead of .00038. Metgapfill is doing things correct and inserting 380/1e6 where data are missing. Then met2model is taking the gapfilled values, which are correct, and dividing by 1e6, giving us the 3.8e-10.

**Comment by mdietze** [comment]
@tonygardella @jam2767 can this and #332 be closed? In other words, are these two issues resolved in v1.4.4 VM?

**Comment by tonygardella** [comment]
Just double checked with 1.4.4. Local run with Ed, Ameriflux works fine with no errors.
