### ISSUE TITLE
Postgres error

### ISSUE THREAD

**Issue by rykelly** [PecanProject/pecan#683]
Anyone get this error yet?

``` R
2015-11-04 21:06:20 SEVERE [utils.R#50: logger.severe] :
   Error executing db query 'UPDATE runs SET finished_at = NOW() WHERE id = 1000327079'
   errorcode=0 message='FATAL: terminating connection due to administrator command FATAL:
   terminating connection due to administrator command '
Error in logger.severe(paste("Error executing db query '", query, "' errorcode=",  :
  Error executing db query 'UPDATE runs SET finished_at =  NOW() WHERE id =  1000327079' errorcode=0 message='FATAL:  terminating connection due to administrator command
FATAL:  terminating connection due to administrator command
```

Happened to me during a long PDA that was running on `pecan2` but sending jobs to `geo`. It had also been happening to me sporadically while I was working on the code last week, but I had just assumed it was random bugs, failing to close DB connections during numerous test runs, etc. This time the error came after 116 successful consecutive runs, so I don't think it's my code. 

Any ideas?

**Comment by mdietze** [comment]
here's my guess: There have been some issues with too many db connections being opened on psql-pecan due to sync scripts that would start but not finish. As a result I've had to manually kill all database connections and restart psql a few times over the last few weeks, so it's quite likely that I killed your db connection under the false assumption that no one had jobs (since no one HERE had jobs). Let me know if this continues to happen -- one thing I did was to add a 'clean up' command in cron (at Rob's advice) to kill rogue sync jobs, but if I did it incorrectly it might end up killing all connections periodically.

**Comment by ryankelly-uiuc** [comment]
Sounds good; I'll let you know if it comes up again.

**Comment by dlebauer** [comment]
@mdietze could you please post the contents of the clean up script or put
it in the repository?

**Comment by mdietze** [comment]
This is just something Rob posted on gitter a few days back:

19 * * * * ps -ef | grep kooper | grep -v grep | grep psql | awk '{ print $2 }' | xargs --no-run-if-empty kill

Obviously you have to change the first grep to the user that runs the sync script (I run mine as postgres)

**Comment by ashiklom** [comment]
Good to keep around as a reference, but no need to keep it as an open issue.
