### ISSUE TITLE
Pecan 1.4.4 Web Interface Produces Model Error when Using Conversion

### ISSUE THREAD

**Issue by gtomic2** [PecanProject/pecan#754]
I get a model error when using the web interface at the Tully site with the sipnet model. 

 "Error: no climate data in sipnet.clim
mv: cannot stat '/home/carya/output//PEcAn_99000000030/run/99000000904/sipnet.out': No such file or directory " 

Steps to reproduce. 

Host: pecan64
Model: SIPNET (unk) 
Conversion: True 
Site: Tully_willow

PFT: Temperate.deciduous
Start date: 2013/01/01
End date: 2013/12/31

Sipnet.climna: Use NARR
Use Browndog : True

**Comment by tonygardella** [comment]
I was able to reproduce this bug. ```sipnet.clim``` is empty so  it seems met.process/browndog is not producing the correct model specific NARR met file. Browndowg with Ameriflux works and Sipnet works with other met drivers so the issue seems to be exclusive to this combination of model and met driver.

**Comment by mdietze** [comment]
Unfortunately, the issue is not model specific -- If I select NARR + BrownDog I can reproduce the bug with other models at other sites and for other years.

In the mean time, PEcAn 1.4.5 VM should be re-released (with a small bug fix) as soon as @robkooper gets back from vacation (Monday?) and that provides support for CRUNCEP as well as NARR, which should allow you to run at this site while we sort out what's wrong on Brown Dog.

**Comment by robkooper** [comment]
Can you see if this is an issue, see http://pecan-dev.ncsa.illinois.edu/pecan/05-running.php?workflowid=99000000010
