### ISSUE TITLE
Ensemble analysis fails for ensemble size 1 on pecan2

### ISSUE THREAD

**Issue by ashiklom** [PecanProject/pecan#763]
Whenever I try to do single-member ensembles on `pecan2`, the run fails on the ensemble analysis step.

Here are two representative workflow ID's:

[1000001406](https://pecan2.bu.edu/pecan/08-finished.php?workflowid=1000001406) -- Sipnet, at Harvard Forest.

[1000001409](https://pecan2.bu.edu/pecan/08-finished.php?workflowid=1000001409) -- Dalec, at Willow Creek.

**Comment by mdietze** [comment]
So for 1-1406, the odd thing is that the error is:

no netCDF files of model output present for runid = 1000419687

but there ARE netcdf files that can be visualized.

**Comment by ashiklom** [comment]
This may be a user-specific (i.e. just for me) problem...or a larger issue with the ensemble analysis, because I haven't been able to get any ensemble analysis running, regardless of the size.

The latest fail is [1000001423](https://pecan2.bu.edu/pecan/08-finished.php?workflowid=1000001423).

**Comment by ashiklom** [comment]
This is the error from `workflow.Rout`:

```
[1] "----- Variable: NPP"
[1] "----- Running ensemble analysis for site:  Harvard Forest EMS Tower/HFR1 (US-Ha1)"
Error in hist.default(unlist(ensemble.output), xlab = units, main = "",  : 
  invalid number of 'breaks'
Calls: run.ensemble.analysis -> hist -> hist.default
```

**Comment by ashiklom** [comment]
Digging further, looks like `ensemble.output....Rdata` is a list of `NaN`s. I guess this may be related to Mike's earlier comment.

**Comment by ashiklom** [comment]
@tonygardella Was able to isolate the problem to the `get.results` function.

**Comment by ashiklom** [comment]
OK, after some digging, here's the issue: The execution of SIPNET is ignoring the dates that I told it to run and is running from 1999 to 2002 regardless.

@tonygardella found that everything works fine with Ameriflux, so this is an issue in the default SIPNET met.

**Comment by mdietze** [comment]
Update: deleted the met NARR_SIPNET_site_0-758 because the file itself, and the associated dbfiles record, were for 1999-2002 but the Inputs record was for 2000-2013. Have not idea how that happened but starting over seems far simpler than fixing. Should look out for other examples like these, as they may be lurking from during the NARR development phase.

Longer standing but oft-forgotten issue: SIPNET's met files exist as single large files and write.config.SIPNET doesn't subset the input met to just the years and dates requested. Code to subset SIPNET met exists from the early SDA work. Will spin off another issue for this
