### ISSUE TITLE
read.ensemble.output fails for ED git (on geo)

### ISSUE THREAD

**Issue by ashiklom** [PecanProject/pecan#794]
ED run fails on ensemble step because no netcdf files are found. If I understand PEcAn correctly, this is because the `model2netcdf` (or whatever) conversion function hasn't run for ED. Otherwise, the model runs without issue and produces output in the specified directory, just not the netcdf files.

A reference run is [1000001467](https://pecan2.bu.edu/pecan/08-finished.php?workflowid=1000001467).

And here is the relevant part of the Rout file:

```
...
2016-04-12 18:21:26 DEBUG  [remote.copy.from] : 
   rsync '-a' '-q' '-e' 'ssh -o 
   ControlPath="/fs/data2/output//PEcAn_1000001467/tunnel/tunnel"' 
   'geo.bu.edu:/projectnb/dietzelab/pecan.data/output/ashiklom/1000001467/out/1000440739' 
   '/fs/data2/output//PEcAn_1000001467/out' 

  |                                                                            
  |======================================================================| 100%> 
> # Get results of model runs
> if (status.check("OUTPUT") == 0) {
+   status.start("OUTPUT")
+   get.results(settings)
+   status.end()
+ }
2016-04-12 18:21:28 INFO   [read.ensemble.output] : 
   reading ensemble output from run id: 1000440739 
2016-04-12 18:21:28 WARN   [read.output] : 
   no netCDF files of model output present for runid = 1000440739 in 
   /fs/data2/output//PEcAn_1000001467/out/1000440739 will return NA 
2016-04-12 18:21:28 INFO   [read.output] : 
   NPP Mean: NaN Median: NaN 
> 
> # Run ensemble analysis on model output. 
> if (status.check("ENSEMBLE") == 0) {
+   status.start("ENSEMBLE")
+   run.ensemble.analysis(TRUE)    
+   status.end()
+ }
[1] "----- Variable: NPP"
[1] "----- Running ensemble analysis for site:  Willow Creek (US-WCr)"
Error in hist.default(unlist(ensemble.output), xlab = units, main = "",  : 
  invalid number of 'breaks'
Calls: run.ensemble.analysis -> hist -> hist.default
```

**Comment by robkooper** [comment]
Looking at the log file it shows model2netcd failed:

```
> require (PEcAn.ED2)
Loading required package: PEcAn.ED2
Loading required package: PEcAn.utils
Loading required package: abind
Loading required package: plyr
Loading required package: XML
Loading required package: ggplot2
Loading required package: randtoolbox
Failed with error:  'package 'randtoolbox' could not be loaded'
In addition: Warning messages:
1: package 'PEcAn.ED2' was built under R version 3.2.0 
2: package 'PEcAn.utils' was built under R version 3.2.0 
3: In library(pkg, character.only = TRUE, logical.return = TRUE, lib.loc = lib.loc) :
  there is no package called 'randtoolbox'
> model2netcdf.ED2('/projectnb/dietzelab/pecan.data/output/ashiklom/1000001467/out/1000440739', 45.805925, -90.07961, '2000/07/01', '2000/07/02')
Error: could not find function "model2netcdf.ED2"
Execution halted
```

**Comment by dlebauer** [comment]
Reopening because I am still getting the histogram error when model2netcdf fails. This error is due to the histogram getting a vector of `NaN`

```r
hist(rep(NaN, 10))
Error in hist.default(rep(NaN, 10)) : invalid number of 'breaks'
```

However, model2netcdf should know it has failed, stop, and provide a more useful error message rather than letting the workflow continue and break downstream.

**Comment by mdietze** [comment]
@dlebauer looking at your discussion on Gitter and the run you posted above, this should be opened as a distinct issue -- you're getting a bug in BIOCRO not ED2. The ability of the workflow to catch a model failure is model specific and not related to model2netcdf -- there's something wrong in the BIOCRO job.sh that's not detecting a failed run and passing that info back to PEcAn

**Comment by dlebauer** [comment]
However the detection of a failed model2netcdf output would be useful for
any model

Otherwise the next time any model2netcdf function fails in this way the
failed hist function will be just as uninformative.

**Comment by mdietze** [comment]
But model2netcdf is not a required module or anything PEcAn is running directly. Therefore PEcAn cannot detect an error message from model2netcdf other than via job.sh.  Thus I stick by my original statement -- this is a model-specific problem of failing to detect errors in job.sh. If you want BIOCRO's job.sh to detect that at it's model2netcdf step, that's fine with me.

**Comment by dlebauer** [comment]
@mdietze I am still confused. At a minimum, PEcAn can detect an error when the histogram is drawn. And at that point a more helpful error message could be provided.

For the next person who finds this error:
please add `if(is.nan(x)) logger.error("something helpful about where x came from, like 'model2netcdf failed to produce valid output'")` before the histogram is  drawn.

**Comment by mdietze** [comment]
I'm happy to accept pull requests with more informative error messages, but that error has to be accurate. Technically the ensemble analysis plotting code doesn't know that model2netcdf failed to produce valid output. Indeed, for a given model the model2netcdf function may not even exist. Any error message within a function should be informative, but it also has to be accurate -- it shouldn't inadvertently send someone on what could turn out to be a wild goose chase. A failure to read output could have come from multiple sources (failure of model run to start, model crash, failure of model to write output correctly, failure to convert that to PEcAn standard, failure in pulling the data from the remote server, loss of connection with the remote server, writing the data to the wrong directory, etc). I would agree that MOST of the time the failure is that the model itself crashed, but I've also seen many of the other possible errors pop up from time to time. 

Fundamentally, we need to do a better job at catching errors in job.sh immediately, stop the run, and reporting the error. We don't need to give better hints about a problem in a module that's N steps after the cause of the error.  

That said, I do think we would benifit from better error checking at the end of start.model.runs to detect absent or empty output files so that, at a minimum, the error and message would occur in the module where the error occurred. This would help with the cases where job.sh failed to return an error message or PEcAn failed to detect such message.
