### ISSUE TITLE
Fluxnet 2015 errors

### ISSUE THREAD

**Issue by tonygardella** [PecanProject/pecan#910]
Sipnet/Fluxnet2015 at Niwot Ridge Forest/LTER NWT1 (US-NR1) failed with this error when met2model is executed from met.process:
```
[1] 2004
[1] "vobjtovarid4: error #F: I could not find the requsted var (or dimvar) in the file!"
[1] "var (or dimvar) name: specific_humidity"
[1] "file name: /home/carya/output/dbfiles/Fluxnet2015_CF_gapfill_site_0-772/FLX_US-NR1_FLUXNET2015_SUBSET_HH_1998-2014_1-2.2004.nc"
Error in vobjtovarid4(nc, varid, verbose = verbose, allowdimvar = TRUE) : 
  Variable not found
Calls: remotefunc -> <Anonymous> -> ncvar_get -> vobjtovarid4
Execution halted
[1] 1
[1] "RESULTS: Convert.Input"
[1] 1
NULL
Error in result$file : $ operator is invalid for atomic vectors
Calls: <Anonymous> ... convert.input -> dbfile.input.insert -> basename -> dirname
> proc.time()
   user  system elapsed 
  6.997   0.413   7.661 
```
It seemed like specific humidity is missing and indeed it is. I checked the netcdf files (CF and CF gapfilled) and it wasn't there. I wasn't entirely sure if it was there in the raw csv file though because I wasn't sure about the short names of the variables in that file.

**Comment by tonygardella** [comment]
I tried other sites and one of the errors I got was fixed by @ankurdesai in his current pull request. Another one though occurs when download.Fluxnet2015 is executed from met.process. This is the error I got for  Sipnet/Fluxnet 2015 at Harvard Forest EMS Tower/HFR1 (US-Ha1):
```
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Couldn't resolve host name
Calls: remotefunc ... request_fetch -> request_fetch.write_memory -> <Anonymous> -> .Call
Execution halted
[1] 1
Error in new.files$file : $ operator is invalid for atomic vectors
Calls: <Anonymous> -> dbfile.input.insert -> basename -> dirname
> proc.time()
   user  system elapsed 
  6.381   0.347   7.070 
```

**Comment by ankurdesai** [comment]
@tonygardella I can't replicate your US-NR1 error Fluxnet issues with any other site (US-Syv US-WCr). The latest update downloads the file, gap fills specific humidity based on VPD, and runs sipnet. I wonder if you have some corrupt files in your VM from aborted runs. Delete the CF and gap fill files from /home/carya/output/dbfiles and also from BETY dbfiles and try again. 

The issue with US-Ha1 is tricker. This is because the data is hourly instead of half hourly and hence the file name as HR instead of HH. The same is probably true of US-UMB and US-PFa. Let me see if a simple fix will work.

**Comment by ankurdesai** [comment]
Simple fix won't work because nothing in the JSON query tells you what's in the zip file. So we have to first download the zip file. list contents and check for timestamp. Of course need to make changes if file is already downloaded and test for existence of HR or HH. This will affect both fluxnet2015 and amerifluxlbl until I can fix it.

**Comment by tonygardella** [comment]
@ankurdesai Thank you for checking everything! and I saw the #911. Since Fluxnet is working for other sites then I'll close this issue.
