### ISSUE TITLE
pecan URL needs buttons for pecan and rstudio

### ISSUE THREAD

**Issue by bcow** [PecanProject/pecan#914]
For example, the page that comes up when you enter https://pecan2.bu.edu/ has an explanation of pecan but the links to pecan, rstudio and bety are hard to find. It would be good to have buttons or highlighted text.

**Comment by mdietze** [comment]
I'm going to be more brutal and say that landing page needs a complete rewrite. All the information about the project itself is now on the project webpage or gitbook, so that page should be a landing page to get you to the resources you need locally (pecan, rstudio, bety, shiny) and remotely (gitbook, homepage, and submit a github issue).

@robkooper is that page under version control so we can edit it or just something you have that's part of the VM build?

**Comment by robkooper** [comment]
It is at: https://github.com/PecanProject/pecan/blob/master/documentation/index_vm.html
