### ISSUE TITLE
Problems running the PROSPECT/EDR inversion with parallel=TRUE

### ISSUE THREAD

**Issue by Viskari** [PecanProject/pecan#968]
I have been able to run the RTM PROSPECT/EDR inversion code successfully sequentially, but when I try running invert.auto with parallel set to be TRUE. For some reason in that case, some of the EDR runs start failing because of the input files. Example error messages below.

[1] "Running 3 chains in parallel. Progress bar unavailable"
At line 352 of file radiate_driver.f90 (unit = 22, file = 'reflect_par.dat')
Fortran runtime error: End of file
At line 352 of file radiate_driver.f90 (unit = 22, file = 'reflect_par.dat')
Fortran runtime error: End of file
At line 348 of file radiate_driver.f90 (unit = 21, file = 'trans_par.dat')
Fortran runtime error: End of file
At line 352 of file radiate_driver.f90 (unit = 22, file = 'reflect_par.dat')
Fortran runtime error: End of file

Any suggestions on this front?

**Comment by serbinsh** [comment]
@Viskari this is on our linux server modex correct?

**Comment by Viskari** [comment]
Yep

**Comment by ashiklom** [comment]
Is EDR itself running in parallel? If each instance of EDR needs multiple threads, there could be an issue with then trying to run multiple instances of EDR at the same time, as required by the parallel inversion functionality. 

Alternatively, it could be an issue with multiple instances of EDR trying to read from the same file at the same time, or something to that effect.

**Comment by serbinsh** [comment]
@ashiklom Given my understanding of EDR I dont think it is related to a thread issue, particularly since EDR runs as a compiled executable and should be able to run numerous simultaneous instances, just like standard ED2

But the reading from the same file by simultaneous instances could be an issue.  I suppose we could test by creating X chains versions of the same file and see if we avoid the error on read....

**Comment by ashiklom** [comment]
Yes, but I'm wondering if EDR's internal parallelism would clash with the threads created by R. You're probably right, but it wouldn't hurt to test with an EDR configuration that runs without OMP (if such a thing is possible).

Also, this is a bit of a tangent, but it may be worth thinking about whether or not there's a better way to pass the spectral reflectance characteristics into ED that doesn't require writing and reading additional files. One idea: If the PAR and NIR calculations are the same (which we still need to determine), we could just pass an arbitrary-length leaf optics vector into the ED config XML file (which may be awkward and would lead to bulky config XML files). Another idea: Couple EDR to PROSPECT internally and just pass the scalar PROSPECT parameters to ED(R). Personally, I like this idea because it formalizes the link between leaf optics and relevant physiological traits (e.g. we know changes in SLA affect leaf reflectance, but right now these are not connected in ED). Obviously, we should stick with what we have right now if it works, but these ideas may be worth discussing in the near future.

**Comment by Viskari** [comment]
EDR is not running internally parallel. And even if that was it, the actual error message would be different.

**Comment by serbinsh** [comment]
@Viskari @ashiklom can either of you share the script that isn't working with me and any inputs I need to test it?

**Comment by ashiklom** [comment]
This has been resolved in #1133 .
